services:
  node:
    image: node:21.6-alpine3.18
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - "8081:8081"
    command: "npm run dev"

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
